dist: xenial
language: python
sudo: false
services:
- redis-server
python:
- 3.6
- 3.7
install:
- pip install -U pip setuptools
- pip install -U pipenv codecov
- pipenv install -d --skip-lock --system
- pip install -e .
script: pytest --cov=aioworkers_redis
after_success:
- codecov
before_deploy:
- echo "__version__ = '$(git describe --tags)'" > aioworkers_redis/version.py
deploy:
  provider: pypi
  user: yttrium
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION = 3.6"
  skip_cleanup: true
  password:
    secure: pJKTaRaknP/oOKlGdIkbOXlEfG2AJkmg9VYixLXPCpxeU/Olwy3g+mk/f0e+tvnTSOR3bDwUwQs5pBevEC9ltyYX4j6nO9CLj7yoBggjpB6oXTDkcs58kjN0L82E4qCwWK3UnMDPD3eD2fTNV7OE7gQIfV5QfkksJhhdr+YPIyhJgNqxefQ1J059pB6nCeQKL8a8Qp1oWBVdR3JuXIBZERPxaWrzn5kG/jopqemkDY7bUmGxN8AygA60pGWrlsmU+CrHumiP99dWGFx0pOQcFzB5q9BxiujJ+RO20z0pPlpis1lWZ5FxwJ40l+2SYqUA/XvFASZHBLWHPb9Kf+7acqeCqJ5Evtu7R1/UAklwuViFzyFrKEFIW7D5YmMu1eBzgyeYgnMZJjCaC1TW8qPyPpo6Bp/13gBY0vBpDXsjBjVoHsqBDRaNHBNw80xgtqq/9djWQPw17xA2av+C1VlJ6yW3ClWEtOugCVaF22kwM+vgRB+TTglt5gK8iuhkxe++TYsdeUIY2KoSy5+y0NXP8Kk6T2t8a59hZt/Ugn/dtt754mxKui2MxHY4ZsN9Gihe1pca2kPC03o7NNc20R9ES4LAoZALjpf44VBGXPmGVInFm6G55qrIam183p4e9qxcFDW3howBHp88yTvYvQNpLK6wUvNw9l1VdXGA5p80lg4=
