worker:
  ping:
    cls: aioworkers.worker.base.Worker
    run: worker.run
    autorun: true
    input: queue.pong
    output: queue.ping
    groups: ['ping']
  pong:
    cls: aioworkers.worker.base.Worker
    run: worker.run
    autorun: true
    input: queue.ping
    output: queue.pong
    groups: ['pong']

redis:
  cls: aioworkers_redis.base.Connector
  prefix: pingpong

queue:
  ping:
    cls: aioworkers_redis.queue.Queue
    connection: redis
    key: ping
  pong:
    cls: aioworkers_redis.queue.Queue
    connection: redis
    key: pong
