name: Tests

on:
  push:
    branches:
      - 'master'
    tags: [ '*' ]
  pull_request:
    branches:
      - 'master'

jobs:
  tests:
    strategy:
      max-parallel: 7
      matrix:
        os:
          - ubuntu-latest
        redis-version:
          - '5'
          - '6'
          - '7'
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
        include:
          - os: ubuntu-latest
            redis-version: '6'
            python-version: '3.8'
            coverage: true
            lint: true
          - os: ubuntu-latest
            redis-version: '6'
            python-version: pypy-3.8
          - os: ubuntu-latest
            redis-version: '6'
            python-version: pypy-3.9

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4.1.5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U hatch
      - name: ruff
        if: ${{ matrix.lint }}
        run: |
          hatch run lint:ruff check aioworkers_redis tests
      - name: isort
        if: ${{ matrix.lint }}
        run: |
          hatch run lint:isort -c aioworkers_redis tests
      - name: black
        if: ${{ matrix.lint }}
        run: |
          hatch run lint:black --check --diff aioworkers_redis tests
      - name: mypy
        if: ${{ matrix.lint }}
        run: |
          hatch run lint:mypy aioworkers_redis tests
      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - name: Tests with coverage
        run: |
          hatch run cov
      - name: coverage.xml
        if: ${{ matrix.coverage }}
        run: |
          hatch run coverage xml
      - name: Upload coverage to Codecov
        if: ${{ matrix.coverage }}
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
