name: Tests

on:
  push:
    branches:
      - 'master'
    tags: [ '*' ]
  pull_request:
    branches:
      - 'master'

jobs:
  tests:
    strategy:
      max-parallel: 7
      matrix:
        os:
          - ubuntu-22.04
        redis-version:
          - '5'
          - '6'
          - '7'
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
        include:
          - os: ubuntu-22.04
            redis-version: '6'
            python-version: '3.9'
            coverage: true
            lint: true
          - os: ubuntu-22.04
            redis-version: '6'
            python-version: pypy-3.9

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U hatch
      - name: ruff
        if: ${{ matrix.lint }}
        run: |
          hatch run lint:style
      - name: mypy
        if: ${{ matrix.lint }}
        run: |
          hatch run lint:typing
      - name: Start Redis
        uses: supercharge/redis-github-action@1.8.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - name: Tests with coverage
        run: |
          hatch run cov
      - name: coverage.xml
        if: ${{ matrix.coverage }}
        run: |
          hatch run coverage xml
      - name: Upload coverage to Codecov
        if: ${{ matrix.coverage && github.ref == 'refs/heads/master' }}
        uses: codecov/codecov-action@v5.3.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
